### ISSUE TITLE
text out of bound on home page

### ISSUE THREAD

**Issue by gholadr** [CodeLinkIO/MoveAndWhap#17]
<img width="1286" alt="Screenshot 2022-12-23 at 11 42 28 AM" src="https://user-images.githubusercontent.com/4038613/209400392-a6cad541-3cc2-4033-8d13-2cd78538a052.png">

**Comment by huylocit14054** [comment]
hi @gholadr ,  I cannot reproduce this one. Which resolution are you using?

**Comment by gholadr** [comment]
fixed!
